# Generated by Django 5.1.3 on 2024-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazim',
            name='discount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manish',
            name='discount',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='samay',
            name='discount',
            field=models.BigIntegerField(null=True),
        ),
    ]
