# Generated by Django 5.1.3 on 2024-11-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0002_kazim_discount_manish_discount_samay_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kazim',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manish',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='samay',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
