# Generated by Django 5.1.3 on 2024-11-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0003_alter_kazim_price_alter_manish_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kazim',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manish',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='samay',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
