# Generated by Django 5.1.3 on 2024-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0004_alter_kazim_discount_alter_manish_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazim',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manish',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samay',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
