# Generated by Django 5.1.3 on 2024-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0005_kazim_date_manish_date_samay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='paymentby',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
