# Generated by Django 5.1.3 on 2024-11-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0006_description_paymentby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manish_Khata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
