# Generated by Django 5.1.3 on 2024-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0007_manish_khata'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kazim',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manish',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manish_khata',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samay',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
