# Generated by Django 5.1.3 on 2024-12-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0008_description_times_kazim_times_manish_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='kazim',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manish',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manish_khata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='samay',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
