# Generated by Django 4.2.21 on 2025-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0009_alter_description_date_alter_kazim_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
