# Generated by Django 4.2.21 on 2025-08-31 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khata', '0011_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='times',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='spilt',
            name='payerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_expenses', to='khata.description'),
        ),
    ]
