# Generated by Django 4.2.21 on 2025-08-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0012_spilt_description_payment_alter_description_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='times',
        ),
    ]
