# Generated by Django 4.2.21 on 2025-08-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0013_remove_description_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
