# Generated by Django 4.2.21 on 2025-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='spilt',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
