# Generated by Django 4.2.21 on 2025-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0016_spilt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spilt',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
