# Generated by Django 4.2.21 on 2025-09-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0017_alter_spilt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spilt',
            name='payerid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
