# Generated by Django 4.2.21 on 2025-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0018_alter_spilt_payerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
