# Generated by Django 4.2.21 on 2025-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0019_alter_description_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='spilt',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spilt',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
