# Generated by Django 4.2.21 on 2025-09-02 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khata', '0020_spilt_times_alter_spilt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='desc_user_delete',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spilt',
            name='spilt_user_delete',
            field=models.ForeignKey(default=188, on_delete=django.db.models.deletion.CASCADE, related_name='spilt_expenses', to='khata.description'),
        ),
    ]
