# Generated by Django 4.2.21 on 2025-09-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khata', '0022_alter_description_desc_user_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc_user_delete',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='spilt',
            old_name='spilt_user_delete',
            new_name='expense',
        ),
        migrations.RemoveField(
            model_name='description',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='description',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='description',
            name='paymentby',
        ),
        migrations.RemoveField(
            model_name='description',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='spilt',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='spilt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spilt',
            name='payerid',
        ),
        migrations.RemoveField(
            model_name='spilt',
            name='payment',
        ),
        migrations.AddField(
            model_name='description',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spilt',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='spilt',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to=settings.AUTH_USER_MODEL),
        ),
    ]
