# Generated by Django 4.2.21 on 2025-09-02 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khata', '0023_rename_desc_user_delete_description_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spilt',
            name='expense',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='spilts', to='khata.description'),
        ),
        migrations.AlterField(
            model_name='spilt',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='spilts', to=settings.AUTH_USER_MODEL),
        ),
    ]
