# Generated by Django 4.2.21 on 2025-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0024_alter_spilt_expense_alter_spilt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spilt',
            name='share',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
