# Generated by Django 4.2.21 on 2025-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0025_alter_spilt_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spilt',
            name='share',
            field=models.DecimalField(decimal_places=11, max_digits=11),
        ),
    ]
