# Generated by Django 5.1.3 on 2025-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0027_alter_spilt_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
