# Generated by Django 5.1.3 on 2025-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0029_shopping_equalshare_equalsharesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalsharesplit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equalsharesplit',
            name='times',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
