# Generated by Django 5.1.3 on 2025-09-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0030_equalsharesplit_date_equalsharesplit_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalsharesplit',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalsharessplit', to='khata.equalshare'),
        ),
    ]
