# Generated by Django 5.1.3 on 2025-09-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0032_shopping_payer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kazim',
        ),
        migrations.DeleteModel(
            name='Manish',
        ),
        migrations.DeleteModel(
            name='Manish_Khata',
        ),
        migrations.DeleteModel(
            name='Samay',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
