# Generated by Django 5.1.3 on 2026-04-19 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0034_group_description_group_equalshare_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='start_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='khata.group'),
        ),
    ]
